/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package treecompiler;

import java.util.Scanner;
import java.util.ArrayList;
import java.io.FileInputStream;
import java.io.IOException;

public class App {
    public static void main(String[] args) throws IOException {
        FileInputStream fis = new FileInputStream("C:\\Users\\Jonathan\\Programming\\random_stuff\\Java\\TreeCompiler\\input.txt");
        Scanner scnr = new Scanner(fis);
        Lexer mLexer = new Lexer(outputArrayList(scnr));
        mLexer.runLexer();
        Parser mParser = new Parser(mLexer.getTokenList());
        mParser.runParser();
    }

    public static ArrayList<String> outputArrayList(Scanner scanner) {
        ArrayList<String> outArray = new ArrayList<>();
        while (scanner.hasNext()) {
            String word = scanner.next();
            outArray.add(word);
        }
        return outArray;
    }
}
